name: Java CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      
      - run: chmod +x gradlew
      
      # Etapa modificada: Executa explicitamente o relatório de cobertura
      - run: ./gradlew jacocoTestReport
      
      # Verificação crítica: Lista o conteúdo do diretório de relatórios
      - name: Verify JaCoCo report
        run: |
          echo "Conteúdo do diretório de relatórios:"
          ls -la app/build/reports/jacoco/test/
          echo "Caminho completo do CSV:"
          realpath app/build/reports/jacoco/test/jacocoTestReport.csv
      
      - name: Generate coverage badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: app/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          generate-branches-badge: true
      
      - name: Commit and push the badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update coverage badges'
          add: '.github/badges/*.svg'
      
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: testReport
          path: app/build/reports/tests/test
          retention-days: 1